import Header from './Header5';
import Footer from './Footer';
import Head from 'next/head';
import Image from 'next/image'

const Layout = ( {children} ) => {
  return (
  
    <main className='bg-dark d-flex flex-column min-vh-100'>
    
      <Head>
        <title>OCTA</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.png' />
      </Head>
      <Header />
       
      
      <div className=" text-center ">
       <img src="/n.jpg"  width={1900} height={400} />
       {children}
        
      </div>
      
      <Footer />
    
    </main>
    
    
  );
};

export default Layout;
