import Layout from '../src/components/Layout';
import Head from 'next/head';

//import { useWeb3UserProvider } from "../src/components/userProviderContext";

//import CONTRACT_ADDRESS from '../constants/Contract_Address';
//import { BoxNftContractAddr } from '../config';

export default function Home() {
  
  //const { provider, userAddress } = useWeb3UserProvider()

  return (
    <main className='d-flex flex-column min-vh-100 text-secondary>'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <h1 className="text-secondary">Home</h1>
      </Layout>
    </main>
  );
}